from Recommender import Recommender

recommender = Recommender("AAAAAAAAAAAAAAAAAAAAALsjowEAAAAAX8xdgNjzcZzke0z0baOw8cXDRkc%3DbbhAd6Z6dIwX3iEYWlUukKGOb8tGIOalkw4CwiMOl9ff3fpZd8")
recommendations = recommender.generate_recommendations()

print(recommendations)